spring:
  datasource:
    type: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceWrapper
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:lunar;MODE=MySQL;DATABASE_TO_LOWER=TRUE;USER=sa
    druid:
      initial-size: 10
      max-active: 20
      validation-query: SELECT 1

  h2:
    console:
      enabled: true
      settings:
        # 开启h2 console 跟踪 方便调试  默认 false
        trace: true
        # 允许console 远程访问 默认false
        web-allow-others: true
